services:
  nginx-proxy:
    ports: !override
      - "9000:80"

  nginx-lets-encrypt: !reset null

  misago:
    depends_on: !override
      - postgres-15
      - redis-6

  celery-worker:
    build:
      context: misago
      dockerfile: misago/tencent-cloud.Dockerfile
