version: "3.8"

services:
  nginx-proxy:
    ports: !override
      - "9000:80"

  nginx-lets-encrypt: !reset null

  celery-worker:
    build:
      context: misago
      dockerfile: misago/tencent-cloud.Dockerfile
